---
rnn_config:
  embedding_dim: 256
  rnn_type: "GRU" # LSTM or GRU

  # rnn
  input_size: 256 # size of the recurrent neural network
  hidden_size: 512
  num_layers: 3
  dropout: 0

batch_size: 512
shuffle: True
num_epoch: 10000
which_optimizer: adam
learning_rate: 0.001
weight_decay: 0.0001
percentage: 1.0
